### ISSUE TITLE
README is not ours

### ISSUE THREAD

**Issue by almereyda** [CirclesUBI/o-platform#34]
**Describe the bug**

The README of this project does not state its installation, usage, nor its authors. It is directly taken from the starter template.

**To Reproduce**

1. Check https://github.com/CirclesUBI/o-platform/blob/dev/readme.md

**Expected behavior**

The Readme file is called `README.md` and it is filled with custom, not generic content.

**Comment by codeho** [comment]
it is ours, it is just very very old ;)

**Comment by almereyda** [comment]
I never read past the headline, which says something about a "shell-dapp-starter template", after which I stopped reading, considering the README might just be from the template.

We have an implementation candidate in M-32.
